### ISSUE TITLE
Criação de scrip para inserção de dados

### ISSUE THREAD

**Issue by GuilhermeVolpato** [GuilhermeVolpato/Engenharia-de-dados#4]
O ambiente relacional – origem – deverá ter no mínimo 6 tabelas, 10.000 linhas para cada
tabela principal e com distribuição de datas para os últimos 3 anos (para que no dashboard
tenha informações para compor os KPIs e métricas)

**Comment by GuilhermeVolpato** [comment]
fazendo - Criando script em Python usando Faker

**Comment by GuilhermeVolpato** [comment]
Em chamada no discord, eu e o Guilherme Marques, foi feito script de gerar 10mil registros

**Comment by GuilhermeMSilveira** [comment]
Script no pull request.
